apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: prometheus
  namespace: wego-system
resources:
- app.yaml
- prometheus-gitops-deploy.yaml
- prometheus-gitops-source.yaml
