---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: prometheus
  namespace: wego-system
spec:
  interval: 30s
  url: https://github.com/weaveworks/profiles-catalog/charts/prometheus
